Repository hyf-Group2-fp/Just4Giving, pull requests merged in 2021-05, with the labels that each got.

#23 update npm packages
  package-lock.json
  package.json
Labels: dependencies

#24 update dependencies
  package-lock.json
  package.json
Labels: dependencies

#25 update client dependencies
  client/package.json
Labels: dependencies

#62 3 signupgiver
  README.md
  client/src/App.css
  client/src/App.jsx
  client/src/components/landingpage/Demo.jsx
  client/src/components/register/signupgiver.jsx
  package-lock.json
  package.json
Labels: Front-End, react

#67 working signupgiver page
  client/src/App.css
  client/src/components/register/signupgiver.jsx
Labels: Front-End, react

#63 4 models for DB Sequelize
  .vscode/settings.json
  api/db/db.js
  api/models/Categories.js
  api/models/Goods.js
  api/models/GoodsForMany.js
  api/models/Tags.js
  api/models/User.js
  api/routes/categories.js
  api/routes/goods.js
  api/routes/goodsformany.js
  api/routes/home.js
  api/routes/login.js
  api/routes/tags.js
  api/routes/user.js
  api/scripts/sync.js
  api/server.js
Labels: DB

#72 5 redux
  client/package-lock.json
  client/package.json
  client/src/index.js
  client/src/redux/actions/authActions.js
  client/src/redux/actions/userActions.js
  client/src/redux/actions/userTypeAction.js
  client/src/redux/reducers/authReducer.js
  client/src/redux/reducers/index.js
  client/src/redux/reducers/userReducer.js
  client/src/redux/reducers/userTypeReducer.js
  client/src/redux/store.js
Labels: Front-End, Redux

#71 7 signupneeder
  client/src/App.css
  client/src/App.jsx
  client/src/components/landingpage/Demo.jsx
  client/src/components/register/Signupneeder.jsx
  package-lock.json
  package.json
Labels: Front-End, react

#74 user log in & log out redux
  client/package-lock.json
  client/package.json
  client/src/components/landingpage/Navigation.jsx
  client/src/redux/actions/authActions.js
  client/src/redux/actions/checkProfileAction.js
  client/src/redux/actions/userActions.js
  client/src/redux/actions/userTypeAction.js
  client/src/redux/reducers/authReducer.js
  client/src/redux/reducers/checkProfileReducer.js
  client/src/redux/reducers/index.js
  client/src/redux/reducers/userReducer.js
  client/src/redux/reducers/userTypeReducer.js
Labels: Front-End, Redux

#73 signup needer and giver with redirect and redux
  api/routes/signup.js
  client/package-lock.json
  client/src/App.css
  client/src/components/register/Signupneeder.jsx
  client/src/components/register/signupgiver.jsx
  package-lock.json
Labels: Front-End, react

#70 2 disclaimer
  client/package.json
  client/src/App.css
  client/src/App.jsx
  client/src/assets/disclaimer/Humaaans_3_Characters.png
  client/src/assets/disclaimer/Humaaans_Space.png
  client/src/components/disclaimer/Disclaimer.jsx
  client/src/components/landingpage/Footer.jsx
Labels: Front-End

#83 I signup giver update
  client/src/components/register/signupgiver.jsx
Labels: Back-End, Front-End

#76 login-part front end
  client/src/App.css
  client/src/App.jsx
  client/src/assets/login/signin.png
  client/src/components/login/Login.jsx
Labels: Front-End, react

#90 seeds for DB
  api/routes/goodForMany.js
  api/routes/goods.js
  api/scripts/seed.js
  api/server.js
Labels: DB

#91 login update for redirecting to profiles
  client/src/components/login/Login.jsx
Labels: Front-End, react

#92 Ix seed
  api/models/Categories.js
  api/models/Goods.js
  api/models/GoodsForMany.js
  api/models/Tags.js
  api/routes/goodsformany.js
  api/scripts/seed.js
  api/server.js
  client/src/redux/actions/signInAction.js
  client/src/redux/reducers/signinReducer.js
Labels: DB

#97 login auth
  api/middleware.js
  api/routes/login.js
Labels: Back-End, authentication

#96 Iii item put
  api/routes/updategood.js
  api/server.js
Labels: Back-End

#98 delete good
  api/routes/deletegood.js
  api/server.js
Labels: Back-End, route

#95 Iv posts category
  api/routes/good.js
  api/routes/goods.js
  api/server.js
Labels: Back-End, route

#99 - more redux action
  api/routes/categories.js
  api/routes/signupneeder.js
  api/routes/tags.js
  api/scripts/REDAME.md
  api/scripts/seed.js
  api/scripts/seed1.js
  api/scripts/seed2.js
  api/scripts/seed3.js
  api/scripts/seed4.js
  client/src/App.jsx
  client/src/redux/actions/signInAction.js
  client/src/redux/actions/userInfoAction.js
  client/src/redux/reducers/index.js
  client/src/redux/reducers/signinReducer.js
  client/src/redux/reducers/userInfoReducer.js
Labels: Redux

#100 giver profile
  client/src/App.css
  client/src/App.jsx
  client/src/assets/giver/banner.png
  client/src/components/giver/Giverprofile.jsx
  client/src/components/giver/Itemview.jsx
  client/src/components/giver/Newitem.jsx
  client/src/components/landingpage/Navigation.jsx
  client/src/components/login/Login.jsx
  client/src/components/register/signupgiver.jsx
Labels: Front-End

#105 routes for the categories
  api/routes/categories.js
  api/routes/updategood.js
Labels: Back-End, route

#104 clean the front-end fix bugs
  api/routes/good.js
  api/routes/goods.js
  api/routes/login.js
  api/server.js
  client/src/App.css
  client/src/App.jsx
  client/src/components/giver/Giverprofile.jsx
  client/src/components/giver/ItemView.jsx
  client/src/components/giver/NewItem.jsx
  client/src/components/landingpage/Navigation.jsx
  client/src/components/login/Login.jsx
  client/src/components/login/Secret.jsx
  client/src/components/register/SignUpNeeder.jsx
  client/src/components/register/signUpGiver.jsx
  client/src/redux/actions/signInAction.js
  client/src/redux/actions/signUpAction.js
  client/src/redux/actions/userInfoAction.js
  client/src/redux/reducers/index.js
  client/src/redux/reducers/signUpReducer.js
  client/src/redux/reducers/signinReducer.js
  client/src/redux/reducers/userInfoReducer.js
Labels: Front-End, react

#106 backend validation
  api/routes/goods.js
  api/routes/login.js
  api/routes/signup.js
  api/routes/signupneeder.js
  api/utils/goodValidation.js
  api/utils/registerValidation.js
  api/utils/signupNeederValidation.js
  api/utils/signupValidation.js
  package-lock.json
  package.json
Labels: Back-End

#107 - Fix quality dropdown
  api/models/Goods.js
  api/scripts/seed3.js
  api/utils/goodValidation.js
Labels: Back-End

#117 - 11 goods
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.jsx
  client/src/components/giver/Goods.jsx
  client/src/components/giver/ItemPreview.jsx
  client/src/components/giver/ItemView.jsx
  client/src/components/giver/NewItem.jsx
  client/src/components/landingpage/Navigation.jsx
  client/src/components/register/signUpGiver.jsx
  client/src/redux/reducers/goodsInfoReducer.js
Labels: Front-End, react

#118 2 about us update
  client/src/App.css
  client/src/App.jsx
  client/src/assets/aboutus/Humaaans_3_Characters.png
  client/src/components/aboutus/Aboutus.jsx
  client/src/components/landingpage/About.jsx
  client/src/components/landingpage/Navigation.jsx
Labels: Front-End, react

#119 9 needer profile
  client/src/App.jsx
  client/src/components/giver/Giverprofile.jsx
  client/src/components/giver/ItemPreview.jsx
  client/src/components/needer/NeederProfile.jsx
  client/src/components/register/SignUpNeeder.jsx
  client/src/components/register/signUpGiver.jsx
  package-lock.json
Labels: Front-End, react

#121 modify updategood.js PUT
  api/routes/updategood.js
Labels: Back-End, route

#120 9 categories panel
  api/models/Categories.js
  api/scripts/seed3.js
  client/public/assets/images/categories/babies.png
  client/public/assets/images/categories/books.png
  client/public/assets/images/categories/electronics.png
  client/public/assets/images/categories/food.png
  client/public/assets/images/categories/furnitures.png
  client/public/assets/images/categories/other.png
  client/public/assets/images/categories/sport.png
  client/public/assets/images/categories/tools.png
  client/src/App.css
  client/src/App.jsx
  client/src/assets/categories/open_close.png
  client/src/components/categories/categories.jsx
Labels: Front-End

#122 Contact us
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.jsx
  client/src/components/contactus/contactus.jsx
  client/src/components/giver/Goods.jsx
  client/src/components/giver/ItemView.jsx
  client/src/components/landingpage/Footer.jsx
  package-lock.json
Labels: Front-End, react

#123 9 needer profile
  client/src/App.css
  client/src/components/login/Login.jsx
  client/src/components/register/SignUpNeeder.jsx
  client/src/components/register/signUpGiver.jsx
Labels: Front-End, react

#127 12 contact giver
  api/db/db.js
  api/routes/getGiver.js
  api/routes/sendEmail.js
  api/routes/signup.js
  api/routes/signupneeder.js
  api/server.js
  client/src/App.jsx
  client/src/components/needer/ContactGiver.jsx
  client/src/components/needer/NeederProfile.jsx
  index.js
  package-lock.json
  package.json
Labels: Front-End, react

#129 12 contact giver update
  api/routes/sendEmail.js
  client/src/App.css
  client/src/components/needer/ContactGiver.jsx
Labels: Front-End, react

#128 Review css update
  client/src/App.css
  client/src/App.jsx
  client/src/assets/giver/banner.png
  client/src/assets/giver/user.png
  client/src/components/aboutus/Aboutus.jsx
  client/src/components/contactus/contactus.jsx
  client/src/components/disclaimer/Disclaimer.jsx
  client/src/components/giver/EditItem.jsx
  client/src/components/giver/Giverprofile.jsx
  client/src/components/giver/Goods.jsx
  client/src/components/giver/ItemPreview.jsx
  client/src/components/giver/NewItem.jsx
  client/src/components/landingpage/Demo.jsx
  client/src/components/landingpage/Footer.jsx
  client/src/components/landingpage/Navigation.jsx
  client/src/components/login/Login.jsx
  client/src/components/register/SignUpNeeder.jsx
  client/src/components/register/signUpGiver.jsx
  package-lock.json
Labels: Front-End

#130 adding banner to the needer's page
  client/src/App.css
  client/src/components/categories/categories.jsx
  client/src/components/needer/NeederProfile.jsx
Labels: Front-End
